/**
 * Copyright (C) 2015 Bonitasoft S.A.
 * Bonitasoft, 32 rue Gustave Eiffel - 38000 Grenoble
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2.0 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package org.bonitasoft.web.designer.controller.export.properties;

import lombok.RequiredArgsConstructor;
import org.apache.commons.lang3.StringUtils;
import org.bonitasoft.web.designer.config.UiDesignerProperties;
import org.bonitasoft.web.designer.model.page.Page;
import org.bonitasoft.web.designer.model.page.WebResource;
import org.bonitasoft.web.designer.rendering.GenerationException;
import org.bonitasoft.web.designer.service.PageService;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.*;

import static java.util.stream.Collectors.toList;

@RequiredArgsConstructor
public class PagePropertiesBuilder {

    private final UiDesignerProperties uiDesignerProperties;
    private final PageService pageService;

    public byte[] build(Page page) throws GenerationException, IOException {
        List<String> resources = pageService.getResources(page);

        var properties = new Properties();
        properties.put("name", "custompage_" + page.getName());
        properties.put("contentType", String.valueOf(page.getType()).toLowerCase(Locale.ENGLISH));
        properties.put("displayName", StringUtils.isBlank(page.getDisplayName()) ? page.getName() : page.getDisplayName());
        properties.put("description", page.getDescription());
        properties.put("resources",  resources.toString());
        properties.put("designerVersion", uiDesignerProperties.getVersion());
        var byteArrayOutputStream = new ByteArrayOutputStream();
        properties.store(byteArrayOutputStream, "Generated by Bonita UI Designer");

        return byteArrayOutputStream.toByteArray();
    }

}
