name: Open Studio PR
on:
  workflow_dispatch:
    inputs:
      version:
        description: new version to release (keep --next-path to bump version)
        default: '--next-patch'
        required: true
      baseBranche:
        description: master || dev (Studio Base branch to update)
        default: 'master'
        required: true
  repository_dispatch:
     types: [ github-studio-pr ]
jobs:
  openStudioPR:
    name: Update Studio to bump ui-designer version
    runs-on: ubuntu-latest
    steps:
      - name: Init
        id: init
        run: |
          if [ ${{ github.event.action }} == 'github-studio-pr' ]
          then
              echo "##[set-output name=tagVersion;]$(echo ${{ github.event.client_payload.releaseVersion }})"
              echo "##[set-output name=studioBaseBranch;]$(echo ${{ github.event.client_payload.baseBranch }})"
          else
              echo "##[set-output name=tagVersion;]$(echo ${{ github.event.inputs.version }})"
              echo "##[set-output name=studioBaseBranch;]$(echo ${{ github.event.inputs.baseBranche }})"
          fi
      - name: Print parameter
        id: initParameter
        run: |
          echo "studioBaseBranch => ${{ steps.init.outputs.studioBaseBranch}}"
          echo "tagVersion => ${{ steps.init.outputs.tagVersion}}"
      - name: Check out Studio repository
        uses: actions/checkout@master
        with:
          repository: bonitasoft/bonita-studio-sp
          token: ${{ secrets.GH_TOKEN_PAT }}
      - name: Open Studio PR
        shell: bash
        run: |
          ./releng/update_uid_version.sh ${{ steps.init.outputs.tagVersion }} \
                          --branch-name=${{ steps.init.outputs.studioBaseBranch }} \
                          --github-api-token=${{ secret.GH_TOKEN_PAT }} \
                          --git-user=${{ secret.GIT_USERNAME }} \
                          --git-password=${{ secret.GIT_PASSWORD }}
