name: Crowdin upload files

on:
  # Workflow called by https://github.com/bonitasoft/platform-pipelines
  workflow_call:
    secrets:
      KSM_CONFIG:
        required: true
      BONITA_CI_PAT:
        required: true
  workflow_dispatch:

jobs:
  upload-source-to-crowdin:
    runs-on: ubuntu-24.04
    steps:
      - name: Retrieve secrets from Keeper
        uses: Keeper-Security/ksm-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |
            ${{ vars.KEEPER_CROWDIN_RECORD_ID }}/field/login > env:CROWDIN_PROJECT_ID
            ${{ vars.KEEPER_CROWDIN_RECORD_ID }}/field/password > env:CROWDIN_PERSONAL_TOKEN

      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: bonitasoft/bonita-ui-designer-internal
          token: ${{ secrets.BONITA_CI_PAT }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install gettext
        run: sudo apt-get install -y gettext

      - name: Build pot files
        working-directory: frontend
        run: yarn install && npm run pot

      - name: Concatenate pot files
        run: |
          mkdir -p infrastructure/crowdin/build
          cat `find . -name '*.pot' -print` | msguniq -s > infrastructure/crowdin/build/lang-template.pot

      - name: Upload to crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          push_translations: false
          download_translations: false
          crowdin_branch_name: ${{ github.ref_name }}

      - name: Send message to Slack channel
        if: failure()
        uses: bonitasoft/notify-slack-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          channel-id: ${{ vars.UID_SLACK_CHANNEL_ID }}
          message: |
            :fire: Upload *UID* translations to Crowdin for ${{ github.ref_name }} failed.

            @channel *We need someone* !

            - Add a :fire_extinguisher: if you take the action to resolve the conflicts (only one person is required)
            - Add a :sweat_drops: when it's done (and eventually a :party_parrot:)"
