name: Bump version
on:
  repository_dispatch:
     types: [ github-studio-pr ]
jobs:
  openStudioPR:
    name: Update Studio to bump ui-designer version
    runs-on: ubuntu-latest
    steps:
      - name: Init
        id: init
        run: |
              echo "##[set-output name=tagVersion;]$(echo ${{ github.event.client_payload.releaseVersion }})"
              echo "##[set-output name=studioBaseBranch;]$(echo ${{ github.event.client_payload.baseBranch }})"
      - name: Send message to Slack channel
        uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,ref
        custom_payload: |
          {
            username: 'action-slack',
            icon_emoji: ':octocat:',
            attachments: [{
              color: 'good',
              text: `UI-Designer release ${{ github.event.client_payload.releaseVersion }} success. Next step: Open PR in bonita-studio on branch ${{github.event.client_payload.baseBranch}} repository and close nexus release`,
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
