name: Push to community subtree

on:
  workflow_dispatch: 
    inputs:
      ref:
        type: string
        description: The git ref to push to subtree, can be a branch refs/heads/dev or a tag refs/tags/10.0.0
      ref_name:
        description: The git ref name to push to subtree, can be a branch dev or a tag 10.0.0
        type: string
  push:
    branches: 
      - 'dev'

jobs:
  push-subtree:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
          fetch-depth: 0
      - name: Split community subtree
        uses: claudiodekker/splitsh-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.BONITA_CI_PAT }}
        with:
          prefix: ''
          remote: https://github.com/bonitasoft/bonita-ui-designer.git
          reference: ${{ github.event.inputs.ref_name || github.ref_name }}
          as_tag: ${{ startsWith( github.event.inputs.ref || github.ref, 'refs/tags/') }}